# Basic
name:               "Ciarán McGeady"
title:              "The personal webpage of Ciaran McGeady "
description:        "Welcome to my webpage."


# URL
url:                https://ciarananthony.github.io/about/
baseurl:
#baseurl:            "" #For Root Domain
permalink:          /:year/:month/:day/:title.html

# Markdown
markdown:           kramdown

# Navigation
nav:
  - name:           "home"
    href:           "/"
  - name:           "about"
    href:           "/about"
  - name:           "blog"
    href:           "/blog"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
